#!/bin/bash
if [ -z "$PYFILE" ]; then
    echo "Error: PYFILE environment variable not set."
    exit 0
fi
filename=$(basename -- "$PYFILE")
extension="${filename##*.}"
filename="${filename%.*}"
mkdir -p "__pycache__"
python3 -m compileall -b -x '__pycache__' "$PYFILE"
